name: api
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
 angel_framework: ^2.1.1
 angel_hot: ^2.0.6
 mongo_dart: ^0.4.1
 path: ^1.7.0

dev_dependencies:
  build_runner: ^1.10.0
  build_web_compilers: ^2.11.0
  pedantic: ^1.9.0
